language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - export BOTO_CONFIG=/dev/null
install:
  - pip install -r requirements.txt
# command to run tests
script:
- PYTHONPATH=. python3 -m pytest tests/